# Generated by Django 2.1.4 on 2019-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
