# Generated by Django 2.1.5 on 2019-02-05 08:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(default='', verbose_name='Идентификатор станции')),
                ('d', models.CharField(max_length=500, verbose_name='Координаты svg')),
                ('line', models.ManyToManyField(to='metro_map.Line', verbose_name='Ветка(и)')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.TextField(blank=True)),
                ('data_visit', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metro_map.User')),
            ],
        ),
        migrations.AddField(
            model_name='userstation',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro_map.UserStationsList'),
        ),
        migrations.AddField(
            model_name='userstation',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metro_map.Station'),
        ),
    ]
