# Generated by Django 2.1.5 on 2019-02-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro_map.Station'),
        ),
    ]
